### ISSUE TITLE
Migrate build system

### ISSUE THREAD

**Issue by windytan** [windytan/redsea#90]
Possibility to migrate from autoconf ~~to CMake~~ should be investigated. It would simplify the discovery of external dependencies and creating test cases, and also make the build system more accessible to developers and easier to keep secure.

- [x]  Create a branch replacing automake files with `meson.build`
- [x]  macOS library discovery for Homebrew, MacPorts (esp. liquid-dsp)
- [x]  Debian/Ubuntu library discovery
- [x]  Linux build in CI
- [x]  macOS build in CI
- [x]  Windows (Cygwin) build in CI
- [x]  Windows (MSYS2/MinGW) build in CI
- [ ]  Ensure it works for cross-compilation
- [x]  Update build instructions in README & wiki

**Comment by michal2229** [comment]
Please take a look at meson ( @https://mesonbuild.com ) - it's getting quite popular in FOSS world and I think it is pretty much justified. I used it in a few projects and I find it way easier and more readable/maintainable than CMake.

**Comment by windytan** [comment]
Thanks! I'll check out the alternatives, too. Meson is a new one for me. The biggest plus side of good old CMake would be it's so widely used in C++ projects nowadays, and easily available for many platforms.
